# Generated by Django 3.2.3 on 2021-06-03 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guardians',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('phoneNumber', models.BigIntegerField(null=True, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('idNumber', models.BigIntegerField(null=True, unique=True)),
                ('location', models.CharField(max_length=250)),
                ('dp', pyuploadcare.dj.models.ImageField(blank=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('dob', models.DateTimeField()),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dp', pyuploadcare.dj.models.ImageField(blank=True)),
                ('phone_number', models.BigIntegerField(null=True, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Children',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('dob', models.DateTimeField()),
                ('gender', models.CharField(max_length=30, null=True)),
                ('birth_cert_number', models.BigIntegerField(null=True, unique=True)),
                ('birth_cert', pyuploadcare.dj.models.FileField(blank=True)),
                ('passport', pyuploadcare.dj.models.ImageField(blank=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.CharField(blank=True, max_length=100)),
                ('medical_records', models.FileField(blank=True, upload_to='')),
                ('school_report', models.FileField(blank=True, upload_to='')),
                ('guardian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='children.guardians')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
