# Generated by Django 3.2.3 on 2021-06-08 19:40

from django.db import migrations, models
import django.db.models.deletion
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', pyuploadcare.dj.models.FileField()),
                ('name', models.CharField(max_length=20)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='children.children')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
