# Generated by Django 3.2.3 on 2021-06-01 11:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='age',
        ),
        migrations.AddField(
            model_name='children',
            name='dob',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
