# Generated by Django 3.2.3 on 2021-06-01 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_auto_20210601_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='medical_records',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='children',
            name='school',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='children',
            name='school_report',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
