# Generated by Django 3.2.3 on 2021-06-08 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0002_reports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='medical_records',
        ),
        migrations.RemoveField(
            model_name='children',
            name='school_report',
        ),
        migrations.AlterField(
            model_name='reports',
            name='name',
            field=models.CharField(choices=[('School Fees Report', 'School Fees Report'), ('Report Card', 'Report Card')], default='School Fees Report', max_length=20),
        ),
    ]
