# Generated by Django 3.2.3 on 2021-06-16 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_auto_20210608_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='children',
            name='birth_cert',
        ),
        migrations.RemoveField(
            model_name='children',
            name='birth_cert_number',
        ),
        migrations.AddField(
            model_name='children',
            name='upi_number',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='children',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='reports',
            name='name',
            field=models.CharField(choices=[('School Fees Report', 'School Fees Report'), ('Report Card', 'Report Card'), ('Medical Report', 'Medical Report')], default='School Fees Report', max_length=20),
        ),
    ]
