# Generated by Django 3.2.3 on 2021-06-01 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0003_auto_20210601_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='children',
            name='dob',
            field=models.DateTimeField(),
        ),
    ]
