# Generated by Django 3.2.3 on 2021-06-21 18:40

from django.db import migrations
import pyuploadcare.dj.models


class Migration(migrations.Migration):

    dependencies = [
        ('children', '0004_auto_20210616_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='children',
            name='birth_cert',
            field=pyuploadcare.dj.models.ImageField(blank=True),
        ),
    ]
